sylius_grid:
  grids:
    app_admin_landingpage:
      driver:
        name: doctrine/orm
        options:
          class: Enis\SyliusLandingPagePlugin\Entity\LandingPage
      fields:
        name:
          type: string
          label: app.form.landingpage.name
        slug:
          type: string
          label: app.form.landingpage.slug
        status:
          type: twig
          label: sylius.ui.status
          sortable: ~
          options:
            template: "@SyliusUi/Grid/Field/state.html.twig"
            vars:
              labels: "@SyliusLandingPagePlugin/Label/Status"
      actions:
        main:
          create:
            type: create
        item:
          update:
            type: update
          delete:
            type: delete
        bulk:
          delete:
            type: delete